api-server/.eslintrc.js, api-server/.gitignore, api-server/.prettierrc, api-server/README.md, api-server/nest-cli.json, api-server/package-lock.json, api-server/package.json, api-server/src/app.controller.spec.ts, api-server/src/app.controller.ts, api-server/src/app.module.ts, api-server/src/app.service.ts, api-server/src/main.ts, api-server/test/app.e2e-spec.ts, api-server/test/jest-e2e.json, api-server/tsconfig.build.json, api-server/tsconfig.json
=> api server init

.github/workflows/main.yml
노션 - 문서 - ci/cd 참조
현재 서버 3000번 포트로 개방해놓았는데, 추후 엔진엑스와 연동을 위해 수정할 필요가 있다.
=> Add GitHub Actions workflow for testing, building, deployment

README.md
- 프로젝트 명 및 소개
- ~일단 간략히 적어보았는데, 개발하면서 수정하면 좋을 듯함~
- 프로젝트 명 및 메인 이미지가 확정된 관계로 추가 및 수정함
- 팀원 소개
- 다른 README 보니까 html 태그를 이용하여 크기를 조정한 것으로 보임
- 이는 메인 이미지 추가 등 README 업데이트할 때 수정할 예정
- 기능 소개
- 기능 개발 완료 후 gif와 함께 추가하면 좋을 듯 함
- 개발 환경 세팅
- backend는 수정 필요
- 기술 스택
- 이 외에 추가 필요하면 추가
- 테이블과 이미지로 변경하면 좋을 듯
- 아키텍쳐 구조
- 아키텍쳐 구성이 어느정도 끝나면 이미지 추가
- 바로 merge 하지 않음.
=> docs: README.md 기본 설정

.dockerignore, .github/workflows/main.yml, .gitignore, Dockerfile, codeRunner.js, package-lock.json, package.json
1. 채점 서버 개발 환경 구축 및 초기화
2. git action 설정
=> Scoring server init

.dockerignore, .eslintrc.js, .github/workflows/main.yml, .gitignore, .prettierrc, Dockerfile, nest-cli.json, package-lock.json, package.json, src/app.controller.spec.ts, src/app.controller.ts, src/app.module.ts, src/app.service.ts, src/main.ts, src/scores/scores.controller.spec.ts, src/scores/scores.controller.ts, src/scores/scores.module.ts, src/scores/scores.service.spec.ts, src/scores/scores.service.ts, test/app.e2e-spec.ts, test/jest-e2e.json, tsconfig.build.json, tsconfig.json
컨트롤러를 통해 채점 서버와 연결이 되어야 합니다. 
테스트를 해봐야 하니 api server main에 merge는 하지 말아주세요
=> api server와 scoring server를 연결하는 컨트롤러 생성

.dockerignore, .eslintrc.js, .github/workflows/main.yml, .gitignore, .prettierrc, Dockerfile, nest-cli.json, package-lock.json, package.json, src/app.controller.spec.ts, src/app.controller.ts, src/app.module.ts, src/app.service.ts, src/main.ts, src/scores/scores.controller.spec.ts, src/scores/scores.controller.ts, src/scores/scores.module.ts, src/scores/scores.service.spec.ts, src/scores/scores.service.ts, test/app.e2e-spec.ts, test/jest-e2e.json, tsconfig.build.json, tsconfig.json
=> Api server 초기 배포

.dockerignore, .github/workflows/main.yml, .gitignore, Dockerfile, codeRunner.js, package-lock.json, package.json
=> scoring server 초기 배포

frontend/src/components/gameplay/GameDefaultBox.tsx, frontend/tailwind.config.js
- GameDefaultBox
- tailwind에 lightskyblue 추가
=> [FE] feat: 게임플레이 기본 박스 추가

codeRunner.js
현재 서버가 채점중인지 아닌지 체크하는 기능을 구현했습니다.
메모리 사용량을 확인하여 결과를 보내주는 기능을 구현했습니다.
=> 현재 채점 중인지 아닌지 확인하는 endpoint 추가 및 메모리 사용량에 따른 정답 여부 구현

frontend/package-lock.json, frontend/package.json, frontend/src/assets/theme/EditorTheme.json, frontend/src/components/gameplay/GameDefaultBox.tsx, frontend/src/components/gameplay/GameFooterBox.tsx, frontend/src/components/gameplay/GameHeaderBox.tsx, frontend/src/components/gameplay/GameItemButton.tsx, frontend/src/components/gameplay/GamePlayBox.tsx, frontend/src/components/gameplay/GameProblemIdx.tsx, frontend/src/index.tsx, frontend/src/pages/GamePlayPage.tsx, frontend/tailwind.config.js
- 모나코 에디터를 통해 기능 제공
- 리사이징 기능 제공
- 리사이징 상에서의 resizeobserver 반복 횟수 문제로 인해 임시방편의 해결책 적용
=> 게임 플레이 페이지 퍼블리싱

frontend/src/App.tsx, frontend/src/components/ready/ButtonBox.tsx, frontend/src/components/ready/ChatBox.tsx, frontend/src/components/ready/ChatContent.tsx, frontend/src/components/ready/EmptyCard.tsx, frontend/src/components/ready/ReadyMark.tsx, frontend/src/components/ready/UserCard.tsx, frontend/src/pages/ReadyPage.tsx
- 페이지 작성
- 하위 컴포넌트 작성
- 임시 상태 및 인터페이스 작성 -> 데이터 적용할 때 수정 필요
- tailwind 다소 하드 코딩하여 변경 시 두 번 일하게 될 수 있음
=> 준비 페이지 퍼블리싱

frontend/src/App.tsx, frontend/src/components/loby/LobyHeader.tsx, frontend/src/pages/LobyPage.tsx
=> 로비 페이지 퍼블리싱

frontend/src/components/gameplay/GameDefaultBox.tsx, frontend/src/components/result/ButtonBox.tsx, frontend/src/components/result/CodeViewerBox.tsx, frontend/src/components/result/RankBox.tsx, frontend/src/components/result/RankItem.tsx, frontend/src/components/result/ResultSummaryBox.tsx, frontend/src/pages/ResultPage.tsx
- 화면 좌측에 유저 점수와 다시하기/나가기 버튼
- 화면 우측에 문제 별 코드 확인
=> 결과 페이지 퍼블리싱

codeRunner.js
=> 채점 서버 최신 버전으로 배포

src/app.module.ts, src/auth/guard/admin.guard.ts, src/common/entities/base-table.entity.ts, src/problems/dto/create-problem.dto.ts, src/problems/dto/update-problem.dto.ts, src/problems/entities/problem.entity.ts, src/problems/mocks/repository.mock.ts, src/problems/problems.controller.spec.ts, src/problems/problems.controller.ts, src/problems/problems.module.ts, src/problems/problems.service.spec.ts, src/problems/problems.service.ts, src/scores/scores.service.ts, src/testcases/dto/create-testcase.dto.ts, src/testcases/dto/update-testcase.dto.ts, src/testcases/entities/testcase.entity.ts, src/testcases/mocks/repository.mock.ts, src/testcases/testcases.controller.spec.ts, src/testcases/testcases.controller.ts, src/testcases/testcases.module.ts, src/testcases/testcases.service.spec.ts, src/testcases/testcases.service.ts, src/users/entities/user.entity.ts
1. 문제와 테스트 케이스 테이블 생성 및 연관 추가
2. 문제 엔드포인트, 서비스 생각나는 대로 일단 구현
3. 테스트케이스 엔드포인트, 서비스 생각나는 대로 일단 구현
4. test를 위한 mock 레포지터리 추가 및 테스트 진행
5. AdminGuard 생성
=> 문제 테이블, 테스트케이스 모듈 생성 및 관련 작업 진행

.github/workflows/main.yml, codeRunner.js, package-lock.json, package.json
멀티 프로세스로 여러 요청을 동시다발적으로 처리해도 되지만, 실행 시간이라는 민감한 부분이 있기 때문에 한번에 하나의 요청만 처리할 수 있게 큐를 도입했습니다.
하지만, CPU 하나의 자원을 하나의 프로세스가 전부 사용하진 못할 것이므로, 적절한 프로세스의 개수를 알아내야 합니다.
=> 큐 도입으로 요청을 한번에 하나만 처리할 수 있게 만들었습니다.[임시 PR]

src/app.module.ts, src/problems/dto/create-problem.dto.ts, src/problems/entities/problem.entity.ts, src/problems/mocks/repository.mock.ts, src/problems/problems.controller.ts, src/problems/problems.service.ts, src/scores/dto/score-submission.dto.ts, src/submissions/dto/create-submission.dto.ts, src/submissions/dto/update-submission.dto.ts, src/submissions/entities/submission.entity.ts, src/submissions/mocks/repository.mock.ts, src/submissions/submissions.controller.spec.ts, src/submissions/submissions.controller.ts, src/submissions/submissions.module.ts, src/submissions/submissions.service.spec.ts, src/submissions/submissions.service.ts, src/testcases/dto/create-testcase.dto.ts, src/testcases/entities/testcase.entity.ts, src/testcases/testcases.controller.ts, src/testcases/testcases.service.ts, src/users/entities/user.entity.ts
서브미션 모듈을 생성하였습니다. 기본적인 엔드포인트만 넣었음.
problem 테이블을 약간 수정하였습니다. problemNumber 컬럼 필요 없을 것 같아서 제거함.(problemId로 대체 가능하여 삭제)
엔드포인트를 약간 수정하였습니다.
=> Submission 모듈 생성 및 api 엔드포인트 수정, problem 테이블 수정

frontend/src/api/baseAxios.ts, frontend/src/api/refresh.ts, frontend/src/components/login/LoginInputBox.tsx, frontend/src/store/useLogin.ts
- baseAxios에 intercepter를 통해 검사하도록 변경
- 로그인 되어있을시에만 동작하도록 함수 제작
=> [FE] feature: 로그인 후 타임아웃 시 새 accessToken 발급받도록 변경

frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/api/baseAxios.ts, frontend/src/components/lobby/LobbyRoomListBox.tsx, frontend/src/components/lobby/LobbyUserListBox.tsx, frontend/src/components/protectroute/ProtectRoute.tsx, frontend/src/pages/LobbyPage.tsx, frontend/src/store/useSocket.ts
- socket.io-client를 이용하여 로그인 후 로비 이동 시, 소켓 연결
- lobby_connect 이벤트를 받아 userList, gameRoomList을 받아와서 업데이트
=> [FE] 로비 소켓 연결

package-lock.json, package.json, src/auth/auth.controller.ts, src/auth/guard/bearer-token.guard.ts, src/problems/entities/problem.entity.ts, src/rooms/rooms.gateway.ts, src/rooms/rooms.service.ts, src/scores/scores.service.ts, src/submissions/dto/create-submission.dto.ts, src/submissions/entities/submission.entity.ts, src/submissions/submissions.service.ts
1. refresh token cookie 기반으로 변경
2. 채점 결과 및 반환 부분 수정
3. 문제 테이블 샘플 코드 추가
=> Fixbug scmodulefix

codeRunner.js
=> Update codeRunner.js with status and output

codeRunner.js
=> Refactor console.log statement to use parsed input in codeRunner.js

frontend/package-lock.json, frontend/src/App.tsx, frontend/src/components/player/MusicPlayer.tsx, frontend/src/pages/LobbyPage.tsx
- 배경 음악 플레이어 추가
- 현재는 BGM만 트는 상태라 app.tsx에 추가되어있음.
=> [FE] feature:BGM 플레이어 컴포넌트 추가

frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/components/common/Modal.tsx, frontend/src/components/login/LoginLogo.tsx, frontend/src/components/player/MusicPlayer.tsx, frontend/src/index.tsx, frontend/src/pages/LobbyPage.tsx, frontend/src/pages/LoginPage.tsx
- 애니메이션 추가
- index.tsx로 browserRouter 이동
=> [FE] style: 페이지간 애니메이션 추가

src/scores/scores.service.ts, src/submissions/dto/create-submission.dto.ts, src/submissions/submissions.service.ts, src/testcases/dto/create-testcase.dto.ts
=> Refactor createSubmission method to include

frontend/src/App.tsx, frontend/src/components/SocketProvider.tsx, frontend/src/components/lobby/CreateRoomModal.tsx, frontend/src/components/lobby/Header.tsx, frontend/src/components/lobby/InviteModal.tsx, frontend/src/components/lobby/RoomListBox.tsx, frontend/src/components/lobby/UserListBox.tsx, frontend/src/components/protectroute/ProtectRoute.tsx, frontend/src/components/ready/ButtonBox.tsx, frontend/src/components/ready/ChatBox.tsx, frontend/src/components/ready/UserCard.tsx, frontend/src/pages/LobbyPage.tsx, frontend/src/pages/ReadyPage.tsx
- 방 생성 모달을 통해 방을 생성
- 생성 이벤트 발생하고 응답으로 생성 이벤트를 수신
- useNavigate를 통해 참가 중인 유저 정보 및 방 정보도 이동할 수 있게 함
- 방에서 로비로 나올 때, 같은 방식으로 데이터를 갖고 나와 그 데이터를 화면에 렌더링
=> [FE] 방 생성 후 방 입장

src/rooms/rooms.gateway.ts, src/rooms/rooms.service.ts
방에 혼자 있을 때 퇴장 버튼을 누르면 퇴장이 안되는 문제가 발생했다.
방을 나갈 때 방의 나머지 인원들에게 퇴장 이벤트를 발생시켰는데, 혼자 있다가 나갈 때는 퇴장 이벤트를 발생시켜줄 사람이 없으므로 예외 처리를 했다.
=> [BE] fix: 방을 나갈 때 남은 인원이 없어도 퇴장 이벤트를 발생시키는 문제 수정

frontend/README.md
=> fe-deploy-change-test

frontend/.env.development, frontend/.env.production, frontend/src/api/auth.ts, frontend/src/api/baseAxios.ts, frontend/src/api/refresh.ts
- 엔드포인트 수정
- socket 에 대한 정보도 수정해야함
=> [FE] api 엔드포인트, 빌드 환경 변화로 인한 변경

.github/workflows/front-deploy.yml
github actions 서버에서 빌드한 파일을 scp를 이용해 서버로 전송했다.
전송하기 전 이미 존재하는 배포 파일들을 삭제하고 전송할 수 있도록 했다.
=> 프론트엔드 CI/CD 환경 구축

frontend/src/components/SocketProvider.tsx, frontend/src/components/lobby/RoomListBox.tsx, frontend/src/components/room/ChatBox.tsx, frontend/src/components/room/ChatContent.tsx, frontend/src/pages/RoomPage.tsx
=> [FE] 방 입장 및 채팅 기능 구현

frontend/src/store/useSocket.ts
- 소켓 요청 url 수정
- `/rooms` -> `/api/rooms`
=> [FE] fix: 소켓 요청 url 수정

.github/workflows/api-server-deploy.yml, .github/workflows/scoring-server-deploy.yml
api server와 scoring server 배포를 위한 git action 설정 파일을 수정하고 추가했습니다.
=> [Chore] api server, scoring server 깃 액션 설정

frontend/src/components/room/ButtonBox.tsx, frontend/src/pages/RoomPage.tsx
***작업중***
- 레디 버튼을 클릭하여 사용자의 레디 상태를 토글 할 수 있다
- CSS 적인 부분은 @LEEGURTS 가 해줬으면 좋겠다
=> [FE] 레디 상태 변경

api-server/src/auth/guard/admin.guard.ts
AdminGuard BasicToken -> BearerToken 변경
=> [BE] Fix: AdminGuard 상속 가드 변경

frontend/src/components/room/ButtonBox.tsx, frontend/src/pages/LobbyPage.tsx, frontend/src/pages/RoomPage.tsx
- 버튼(나가기, 레디) 관련 이벤트 함수 ButtonBox.tsx로 이동
- handleStart를 통해 start 이벤트 처리
- user_exit_lobby의 인자 프로퍼티 수정
- 방 제거 시 로직 추가
=> [FE] 방 퇴장 및 게임 시작 페이지 이동 개선

scoring-server/codeRunner.js
예제 케이스면 답을 제공하고, 그렇지 않으면 답을 제공하지 않습니다.
=> [BE] Feat: 예제 케이스에 따라 답 제공

api-server/src/auth/auth.controller.ts
클라이언트 측에서 post 요청으로 쿠키를 받지 못하는 상황 발생.
cors 버그로 추측되는데, 일단 get으로 수정하였다.
=> [BE] Fix: cors 버그 수정

.github/workflows/api-server-deploy.yml
서버 로그 파일을 기록하기 위해 도커 컨테이너 내부에서 호스트의 디렉토리를 마운팅했다.
=> [BE] Chore: api 서버 배포파일 로컬 디렉토리 마운팅

frontend/src/api/baseAxios.ts, frontend/src/api/problem.ts, frontend/src/api/refresh.ts, frontend/src/components/gameplay/CodeEditor.tsx, frontend/src/components/gameplay/Description.tsx, frontend/src/components/gameplay/FooterBox.tsx, frontend/src/components/gameplay/PlayBox.tsx, frontend/src/components/gameplay/gameitem/GameEventHandler.tsx, frontend/src/components/gameplay/problemType.ts, frontend/src/pages/GamePlayPage.tsx, frontend/src/store/useLogin.ts
=> [FE] Feature:채점 api 연동

api-server/package-lock.json, api-server/package.json, api-server/src/main.ts, api-server/src/utils/logger/winston.config.ts
서버의 로그를 기록하기 위해 winston 라이브러릴 활용해 로거 객체를 구현했다.
호스트의 특정 디렉토리를 도커 컨테이너 내부의 경로에 마운트한다. 내부 경로는 환경 변수를 등록해서 코드에 넣어줬다. app.module에 app.useLogger 설정을 통해 NestJS에서 기본적으로 제공하는 로거도 지정한 포맷으로 변환했다.
=> [BE] Feat: api 서버 로거 객체 구현

api-server/src/main.ts, api-server/src/utils/logger/winston.config.ts
=> [BE] chore: 필요없는 의존성 제거, nestFactory 누락 추가

api-server/package-lock.json, api-server/package.json
=> [BE] Chore: moment-timezone 의존성 누락 추가

api-server/src/utils/logger/winston.config.ts
=> [BE] Fix: 로거 설정 오타 수정

frontend/src/api/problem.ts, frontend/src/components/common/SlidePage.tsx, frontend/src/components/room/ReadyMark.tsx, frontend/src/components/room/UserCard.tsx, frontend/src/pages/GamePlayPage.tsx, frontend/src/pages/LobbyPage.tsx, frontend/src/pages/LoginPage.tsx, frontend/src/pages/RoomPage.tsx
=> [FE] Feature: 페이지 슬라이드 모션 추가

frontend/package-lock.json, frontend/package.json, frontend/src/components/gameplay/CodeEditor.tsx, frontend/src/components/gameplay/PlayBox.tsx, frontend/src/pages/GamePlayPage.tsx
- 게임 페이지에서 마크다운으로 출력 결과를 깔끔하게 조정
=> [FE] Feat: 게임 페이지 문제 설명 마크타운 지원

frontend/src/components/lobby/RoomListBox.tsx, frontend/src/components/lobby/UserListBox.tsx, frontend/src/components/room/ButtonBox.tsx, frontend/src/components/room/ChatBox.tsx, frontend/src/components/room/UserCard.tsx, frontend/src/pages/LobbyPage.tsx, frontend/src/pages/RoomPage.tsx, frontend/src/store/useLobby.ts, frontend/src/store/useRoom.ts
- useRoom을 통한 방 상태 전역화
- useLobby를 통한 로비 상태 전역화
- 변경으로 인한 interface 위치 변경 및 통일
- navigate에 state를 담아 넘기는 방식에서 전역 상태 변경 방식으로 변경
=> [FE] feat: 방, 로비 상태 전역화

api-server/src/problems/problems.service.ts, api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.module.ts
join을 통해 testcase의 input, output을 배열 형태로 포함시켜서 문제를 가져온 후 랜덤으로 뽑아서 게임 시작시 클라이언트에 전송한다.
=> [BE] Feature: 게임 시작시 클라이언트에게 문제 전달

api-server/src/problems/problems.service.ts, api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.module.ts
게임이 끝났다는 `game_over` 이벤트를 받아서 유저의 준비 상태와 방의 상태를 초기화하고 로비에 전달했다.
=> [BE] Feature: 게임오버 게이트웨이 설정

frontend/src/components/room/ChatBox.tsx, frontend/src/components/room/ChatContent.tsx, frontend/src/pages/RoomPage.tsx, frontend/src/store/useRoom.ts
- 방 입장, 퇴장 시 메시지 출력
- 유저 레디 상태 변경 시, 유저가 사라진 것처럼 보이는 현상 수정
=> [FE] feat: 방 입장 퇴장 메시지 출력 및 버그 수정

api-server/src/scores/scores.service.ts, api-server/src/submissions/entities/submission.entity.ts
=> [BE] Feat: SubmissionStatus 구현

api-server/src/problems/problems.service.ts
=> [BE] Refactor: 문제와 테스트케이스를 join해서 가져오는 로직 수정

frontend/package-lock.json, frontend/package.json, frontend/src/assets/svg/DelaySvg.tsx, frontend/src/assets/svg/ShuffleSvg.tsx, frontend/src/assets/svg/SmallWordSvg.tsx, frontend/src/assets/svg/StoleEyeSvg.tsx, frontend/src/assets/svg/SwapSvg.tsx, frontend/src/components/common/Modal.tsx, frontend/src/components/lobby/MyInfo.tsx, frontend/src/components/room/UserCard.tsx, frontend/src/pages/LobbyPage.tsx, frontend/src/pages/RoomPage.tsx
=> [FE] Feat: svg props 이름 변경, 아바타 기능 추가

api-server/src/rooms/rooms.gateway.spec.ts
Add ProblemsService and ProblemTable to
RoomsGateway spec
=> [BE] Feat: RoomsGateway 테스트 코드 수정

frontend/src/components/gameplay/problemType.ts, frontend/src/components/room/UserCard.tsx
=> [FE] Fix: 준비 아이콘 위치 버그 수정

api-server/src/scores/scores.service.ts, api-server/src/submissions/dto/create-submission.dto.ts
Add codeHash to CreateSubmissionDto
=> [BE] Fix: CreateSubmissionDto에 codeHash 추가

api-server/src/scores/scores.service.ts
실수로 salt로 암호화했음. sha256 해싱으로 변경
=> [BE] Fix: salt 암호화 -> sha256 해싱으로 변경

api-server/src/rooms/rooms.gateway.ts
Promise가 전달돼서 await를 통해 값을 받은 후 전달하도록 했다.
=> fix: 랜덤 문제 전달되지 않는 문제 수정

api-server/src/users/users.service.ts
Update getMany() to getOne() in UsersService
=> [BE] Fix: User 한명 가져오는데, getMany() 해서 오류 발생. 수정.

scoring-server/codeRunner.js
stdout과는 상관 없이 리턴값으로만 정답 여부 판정 위해 stdout 방식에서 ipc 방식으로 변경합니다.
=> [BE] Feat: solution 함수 리턴값 ipc 전송 방식으로 변경

frontend/src/App.tsx, frontend/src/components/common/BarEffect.tsx, frontend/src/components/gameplay/CodeEditor.tsx, frontend/src/components/gameplay/FooterBox.tsx, frontend/src/components/gameplay/gameitem/GameEventHandler.tsx, frontend/src/components/lobby/RoomListBox.tsx, frontend/src/components/lobby/UserListBox.tsx, frontend/src/components/protectroute/ProtectRoute.tsx, frontend/src/pages/GamePlayPage.tsx, frontend/src/pages/RoomPage.tsx, frontend/tailwind.config.js
- 풀이 성공시 상태 반영
- ap 호출시 자세한 정보 출력되도록
=> [FE] Feat: 채점 관련 기능 개발

api-server/src/scores/scores.service.ts, api-server/src/users/entities/user.entity.ts, api-server/src/users/users.service.ts
=> [BE] Feat: 유저의 성공, 실패 여부를 새로운 컬럼에 저장하는 기능 구현

api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
=> fix: 방 아이디가 제대로 전달되지 않는 문제 수정

api-server/src/rooms/rooms.constants.ts, api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
=> [BE] Fix: 로비 정보에 roomList 전송하지 않는 문제 수정

api-server/src/rooms/rooms.gateway.ts
client.user.name을 제대로 받아오도록 수정했다.
=> [BE] Fix: 구조분해할당 오류 수정

api-server/src/rooms/dtos/rooms.user.dto.ts, api-server/src/rooms/entities/room.entity.ts, api-server/src/rooms/rooms.constants.ts, api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
게임을 시작할 때 아이템을 생성하는 콜백을 `setInterval`을 통해 방 객체에 할당해주었다.
아이템 사용 요청이 오면 서버의 유저가 가지고 있는 아이템 정보와 대조하여 유효한 사용인지 검증했다.
=> [BE] Feature: 아이템 생성, 사용 검증

api-server/src/rooms/entities/rooms.user.entity.ts, api-server/src/rooms/rooms.constants.ts, api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
dm 게이트웨이의 에러처리를 서비스단으로 분리하고 socketId를 사용해 메시지를 전송하도록 했다.
=> [BE] Refactor: dm 기능 에러처리 분리

api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
=> [BE] Refactor: 강퇴 게이트웨이

frontend/src/components/protectroute/ProtectRoute.tsx, frontend/src/pages/LobbyPage.tsx, frontend/src/pages/RoomPage.tsx
- 룸 아이디 삭제 위치 변경을 통해 정상적으로 페이지 보호가 작동하도록 수정
=> [FE] Refactor: RoomId 삭제 위치 수정

api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
clearInterval을 이용해 제거해줬다. 아이템이 전송되지 않는 문제를 확인하기 위해 로그를 찍었다.
=> [BE] Fix: 아이템 생성 타이머 제거 메서드 수정, 로깅

api-server/src/rooms/rooms.gateway.ts
설정해둔 네임스페이스의 소켓 매퍼로부터 가져올 수 있도록 수정했다.
=> [BE] Fix: 소켓 객체 네임스페이스 문제 수정

api-server/src/rooms/rooms.gateway.ts
=> Fix: 네임스페이스 경로 수정

api-server/src/rooms/rooms.gateway.ts
start 함수가 비동기 함수라서 외부의 ready도 비동기 함수로 수정해주고 await로 start 함수를 실행시키도록 변경했다.
=> [BE] Fix: 비동기 처리 수정

api-server/src/rooms/rooms.service.ts
room 메서드를 통해 객체를 가져오고 내부에서 에러처리를 해줬다.
=> [BE] Fix: 방 객체 가져올 때 예외처리 통합

api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
방 입장시 존재하지 않는 방이면 에러를 반환하도록 했다.
=> [BE] Fix: 방 입장시 예외처리 추가, 테스트용 로그

api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
게임을 시작해서 /game 으로 이동할 때는 방에서 퇴장하지 않도록 예외처리를 했다.
=> [BE] Fix: 소켓 재연결 조건 추가

api-server/src/rooms/rooms.constants.ts, api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
이벤트 응답을 반환할 때 어떤 이벤트인지도 반환하게 했다.
=> [BE] Refactor: 사용하지 않는 로그 삭제, 이벤트 타입 반환 추가

api-server/src/rooms/rooms.gateway.ts
=> [BE] Fix: 로비, 방 정보 반환 오류 수정

api-server/src/rooms/rooms.constants.ts, api-server/src/rooms/rooms.gateway.ts
=> [BE] Refactor: 아이템 첫 분배 setTimeout으로 변경

scoring-server/codeRunner.js, scoring-server/memoryTracker.js, scoring-server/package-lock.json, scoring-server/package.json
=> [BE] Feat: 런타임 동안에, memory track 기능 추가.

api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
=> [BE] Feat: 초대 이벤트 응답에 방 이름, 초대한 유저 이름 추가

api-server/src/submissions/submissions.service.ts
=> [BE] Fix: submission의 hashcode select에서 삭제

api-server/src/rooms/rooms.gateway.ts
API 변경에 따라 웹소켓 서버에서 실행, 제출을 구분해줬다.
=> [BE] Fix: 실행, 제출 구분

api-server/src/rooms/rooms.gateway.ts
=> [BE] Fix: 통과시 랭킹 매기는 로직, 로깅

api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
방에 입장해있는 사용자가 다시 입장 요청을 시도했을 때 거부하는 예외를 발생시킨다.
=> [BE] Feat: 방 입장 예외처리 추가

api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
=> [BE] Fix: 통과한 유저는 아이템을 받지 않도록 수정

api-server/src/rooms/rooms.gateway.ts
게임을 시작할 때 전체 플레이 수가, 최초로 문제를 풀었을 때 승리 횟수가 증가하는 기능을 추가했다.
=> [BE] Feat: 전체 플레이, 승리 횟수 증가

frontend/src/components/lobby/CreateRoomModal.tsx, frontend/src/components/protectroute/ProtectRoute.tsx, frontend/src/components/protectroute/preventBack.ts
=> [FE] Feat: 뒤로가기 기능 차단

api-server/src/rooms/rooms.gateway.ts
테스트용으로 유저가 1명이라도 게임이 가능하게 했던 것을 변경했다.
=> [BE] Fix: 유저가 2명 이상부터 게임을 시작할 수 있게 변경

frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/components/lobby/CreateRoomModal.tsx, frontend/src/components/lobby/RoomListBox.tsx, frontend/src/components/login/InputBox.tsx, frontend/src/components/protectroute/ProtectRoute.tsx, frontend/src/components/protectroute/preventBack.ts, frontend/src/pages/GamePlayPage.tsx, frontend/src/pages/RoomPage.tsx, frontend/src/store/useSocket.ts
- 뒤로가기 동작 안되도록 수정
- 애니메이션 도중에도 안되도록 수정함.
=> [FE] Feat: 뒤로가기 동작 방어

frontend/src/components/room/ButtonBox.tsx, frontend/src/components/room/ChatBox.tsx, frontend/src/pages/RoomPage.tsx
- 게임 시작 후 초대, 나가기 버튼 비활성화
- 버튼 자체를 비활성화하는 것이 아닌 핸들러 함수에서 판단
- 채팅 입력 글자 수 제한
=> [FE] feat: 게임 시작 후 인터렉션 방지

frontend/src/components/gameplay/CodeEditor.tsx, frontend/src/components/gameplay/gameitem/GameEventHandler.tsx, frontend/src/components/gameplay/gameitem/gameItemHandler.ts, frontend/src/components/gameplay/gameitem/gameItemReducer.ts
=> [FE] Feat: 미구현 아이템 구현

api-server/src/users/users.controller.spec.ts
유저 컨트롤러에 대해서 유닛 테스팅 코드와 e2e 테스팅 코드를 작성했습니다.
=> [BE] Feat: Unit test, e2e test code 작성
