boostcampwm2023/web06-CodeClash

package.json, src/auth/auth.controller.spec.ts, src/auth/auth.service.spec.ts, src/scores/scores.controller.spec.ts
nestjs 기본 jest 설정에 문제가 있다고 합니다.
상대 경로로 설정되어 있는 것들을 잘 잡지 못하여 생기는 버그 같습니다 관련된 링크를 첨부합니다.
https://stackoverflow.com/questions/50171412/absolute-paths-baseurl-gives-error-cannot-find-module/51174924#51174924
수정하고 테스팅 실패를 해결했습니다.
=> nestjs jest 설정 변경 및 테스트 실패 해결

src/rooms/rooms.gateway.ts, src/rooms/rooms.service.ts
서버에서 방을 담은 리스트에 인원이 0명인 방이 계속 남아있었다. 방을 나갈 때 인원이 0명인지 확인해서 리스트에서 지워주도록 수정했다.
유저가 방에 입장할 때 roomInfo를 추가로 전달하도록 수정했다.
=> [BE] fix: 방 입/퇴장시 정보 갱신 문제 수정

src/auth/auth.controller.ts, src/problems/problems.controller.ts, src/scores/scores.controller.ts, src/submissions/submissions.controller.ts, src/testcases/testcases.controller.ts, src/users/users.controller.ts
엔진엑스에서 static 파일 서빙과 api 엔드포인트 경로를 구분하기 위해, api 서버의 엔드포인트에 api/를 붙혔습니다.
=> 엔드포인트 경로 api/...로 변경

src/problems/dto/create-problem.dto.ts, src/scores/scores.controller.ts, src/scores/scores.service.ts
1. api/scores/grade로 채점 요청 가능
2. 문제 검색 시, 문제 아이디가 없으면 에러 던짐.
3. create-problem dto에 samplecde 추가
=> 라우팅 url 수정되지 않은 부분 수정 및 에러 헨들링 부분 추가

src/rooms/rooms.gateway.ts
유저가 나간 후의 userCount는 하나가 줄어드는데 그것이 반영되지 않았다.
유저가 1명 있다가 나갔을 때 userCount가 0이 돼야 하는데 1이 돼서 조건문이 실행되는 문제가 발생하므로 수정했다.
=> [BE] fix: 방을 나가기 전의 userCount를 받아오는 문제

api-server/src/rooms/rooms.gateway.ts
유저가 나간 후의 userCount는 하나가 줄어드는데 그것이 반영되지 않았다.
유저가 1명 있다가 나갔을 때 userCount가 0이 돼야 하는데 1이 돼서 조건문이 실행되는 문제가 발생하므로 수정했다.
디렉토리 구조 변경을 위해 이전 사항을 되돌리고 다시 동일한 PR을 넣었다.
=> [BE] fix: 방을 나가기 전의 userCount를 받아오는 문제 #111

api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
방에 혼자 있을 때 나가면 roomList에서 삭제된다. 그 후 getGameRoom 메서드에서 roomId로 조회하는데 undefined이므로 리턴값에서 undefined의 속성값을 조회하는 오류가 발생한다.
=> [BE] fix: 방 퇴장 시 빈 방의 프로퍼티를 조회하는 문제 수정

api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
방이 없어졌을 때 없어진 방에 대한 정보를 로비의 유저들이 받을 수 있게 했다.
나가기 버튼 뿐만 아니라 브라우저를 꺼서 종료했을 때도 handleDisconnect에서 로비에 있는 유저들에게 정보를 전송하도록 했다.
=> [BE] fix: 방이 없어지는 경우 로비에 있는 유저들에게 없어진 방 정보 전송하지 않는 문제

api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
handleDisconnection에서 exitRoom을 실행할 때 socket.rooms와 socket.data가 초기화되므로 예외 처리를 했다.
=> [BE] Fix: socket.data가 undefined 경우 예외처리

api-server/src/rooms/rooms.gateway.ts
roomId와 아이템 enum을 받아서 해당 방의 유저들에게 브로드캐스팅한다.
=> [BE] Feature: 게이트웨이 유저 아이템 사용 처리 구현

api-server/src/rooms/rooms.gateway.ts
게임을 시작한 방은 로비에서 가려야 하므로 방의 ID를 전송했다.
=> [BE] Feature: 게임 시작시 로비에 게임 시작한 방 전송

api-server/src/problems/problems.service.ts, api-server/src/rooms/rooms.gateway.ts
전부 가져온 다음 어플리케이션 레벨에서 랜덤으로 뽑는 것보다는 쿼리에서 랜덤으로 뽑아오는 게 낫다는 판단을 했다. 쿼리빌더를 사용해 order by RAND()를 통해 가져오도록 수정했다.
=> [BE] Refactor: 랜덤으로 문제 가져오는 로직 수정

api-server/src/problems/problems.service.ts
쿼리에서 testcase.input, testcase.output을 select하니까 케이스를 하나만 가져오는 문제가 발생했다. 쿼리상에서 일대다 관계의 테이블을 조인했을 때 특정 칼럼만 가져오는 방법을 알아내지 못해서 map 함수를 이용해 필터링하도록 수정했다.
=> [BE] Fix: 문제의 테스트케이스를 하나만 가져오는 문제

api-server/package-lock.json, api-server/package.json, api-server/src/rooms/entities/room.entity.ts, api-server/src/rooms/rooms.constants.ts, api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
예외 필터를 전역화해서 Gateway 클래스 위에 한 번만 써주도록 변경했다.
`handleConnection`에서 로비 입장까지 같이 해줬던 것을 분리해줬다.
방에 입장할 때 정보도 같이 받아오도록 했는데 정보를 받아오는 로직을 분리했다.
이벤트 응답을 emit으로 전달했는데 return으로 전달하도록 변경했다.
=> [BE] Feat: 예외 필터 전역화, 로비 입장 소켓 연결과 분리, 방 입장과 정보 받아오는 로직 분리, 이벤트 응답을 return으로 전달

api-server/src/rooms/dtos/rooms.user.dto.ts, api-server/src/rooms/entities/room.entity.ts, api-server/src/rooms/entities/rooms.user.entity.ts, api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
service 계층에서 소켓을 직접적으로 다루는 것은 적절하지 않다고 판단했다. 게이트웨이 단으로 책임을 옮기기 위해 연관된 모든 메서드들을 수정했다. RoomsUserDto와 엔티티를 정의해서 다룰 수 있도록 했고, socketId만 따로 담아서 socket.io의 자체적인 매핑 기능을 통해 필요할 때 게이트웨이 단에서 소켓을 찾을 수 있도록 수정했다.
=> [BE] Refactor: 방의 userList에 소켓이 아닌 커스텀 객체를 담도록 수정

api-server/src/rooms/rooms.constants.ts, api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
방을 입퇴장할 때 로비의 있는 유저들의 방 유저카운트 정보가 갱신되도록 했다.
방 제목을 설정하지 않고 생성했을 때 기본 방 제목을 설정해줬다.
=> [BE] Feat: 방 입퇴장시 유저카운트 갱신, 기본 방 제목 추가

api-server/src/rooms/rooms.service.ts
게임 진행 중 유저들이 전부 퇴장하여 방이 삭제될 때 아이템 생성 타이머도 삭제해주도록 했다.
=> [BE] Feat: 아이템 생성 타이머 자동삭제

api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
존재하지 않는 방에서 나갈 수 없다는 로그가 찍히면서 서버가 다운되는 현상이 발생했다.
소켓 연결이 끊길 때 handleDisconnect 내부에선 WsException을 자체적으로 처리하지 못한다. 따라서 에러를 클라이언트에 보내지 못하고 서버가 다운된다. 그래서 handleDisconnect 내부에서 exitRoom을 실제로 방이 존재할 때만 처리해주도록 예외처리를 했다.
=> [BE] Fix: 서버가 간헐적으로 종료되는 문제

api-server/src/rooms/rooms.gateway.ts
server 객체의 sockets는 네임스페이스를 가리키는 것이기 때문에 그 안에서 sockets로 한 번 더 들어가면 소켓을 매핑한 객체가 나온다. io.sockets.sockets와 같이 접근해야 한다.
=> [BE] Fix: 소켓 객체를 제대로 불러오지 못하는 문제

api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
데코레이터를 이용해 socket.io 서버 객체를 생성했을 때 소켓 ID를 통해 소켓 객체를 가져오는 게 자꾸 오류가 나서 자체적인 소켓 매퍼 객체를 다시 생성해서 사용한다.
=> [BE] Fix: 소켓 매퍼 객체 생성

api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.service.ts
setInteravl 콜백으로 넘길 때 이미 한 번 실행하므로 아이템이 중복 전달됐다.
=> [BE] Fix: 아이템 생성 중복 실행

api-server/src/rooms/rooms.gateway.ts
기존에는 60초 후에 하나가 전달됐는데 시작했을 때 바로 1개를 전달하도록 했다.
=> [BE] Feat: 게임 시작시에도 아이템 1개 전달

api-server/src/rooms/rooms.gateway.ts
start를 emit하기 전에 create_item을 보냈기 때문에 순서를 조정했다.
=> [BE] Fix: 아이템 분배 순서 변경

api-server/src/rooms/dtos/rooms.user.dto.ts, api-server/src/rooms/entities/rooms.user.entity.ts, api-server/src/rooms/rooms.constants.ts, api-server/src/rooms/rooms.gateway.ts, api-server/src/rooms/rooms.module.ts, api-server/src/rooms/rooms.service.ts
클라이언트에서 코드를 제출하면 채점 서버에 API 요청을 해서 결과를 받고, 통과하면 유저 정보에 통과했다고 등록한다. 처음으로 통과한 유저인 경우엔 방의 카운트다운을 시작한다.
통과했을 때 그 방에서의 등수를 기록하고, 결과 페이지로 이동할 때 유저네임과 순위를 보내준다. 게임을 시작할 때 방 정보, 유저 정보를 초기화한다.
=> [BE] Feat: 제출 게이트웨이, 유저 순위, 게임 종료 카운트다운
